export const metadata = {
  title: 'Terms of Service | Aura SaaS Insights',
  description:
    'Read the full Terms of Service for Aura SaaS Insights, covering acceptable use, disclaimers, intellectual property, and governing law.',
};
import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[var(--bg-color)] text-[var(--text-primary)] px-6 py-20 flex justify-center">
      <div className="max-w-3xl w-full">
        <h1 className="text-4xl font-bold tracking-tight mb-3">Terms of Service</h1>
        <p className="text-[var(--text-secondary)] text-sm mb-12">
          Last updated: April 17, 2025 &nbsp;&bull;&nbsp; Please read these terms carefully before using Aura.
        </p>

        <div className="prose prose-invert prose-lg prose-headings:text-[var(--accent-color)] opacity-90 leading-relaxed font-sans editorial-prose space-y-2">

          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using Aura SaaS Insights (&quot;Aura,&quot; &quot;the Service,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) at aurarevenue.com, you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to all of these Terms, you may not access or use the Service. These Terms apply to all visitors, users, and others who access or use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Aura provides an interactive, browser-based SaaS financial projection tool that allows users to model Monthly Recurring Revenue (MRR) growth, churn attrition, and cumulative revenue trajectories over a defined time horizon. The Service is provided free of charge and is supported by third-party advertising.
          </p>
          <p>
            All calculations performed by the Service are based on standard mathematical compounding formulas applied to user-supplied inputs. The Service does not connect to any external financial data sources, brokerage accounts, or live business metrics.
          </p>

          <h2>3. Financial Disclaimer — Not Financial Advice</h2>
          <p>
            <strong className="text-white">THE PROJECTIONS GENERATED BY AURA ARE FOR EDUCATIONAL AND PLANNING PURPOSES ONLY. THEY DO NOT CONSTITUTE FINANCIAL ADVICE, INVESTMENT ADVICE, ACCOUNTING ADVICE, OR LEGAL ADVICE.</strong>
          </p>
          <p>
            The projection outputs are hypothetical illustrations based solely on the mathematical formula applied to the inputs you provide. Actual business performance depends on numerous factors outside this model, including market conditions, competitive dynamics, operational execution, macroeconomic environment, and product-market fit. We strongly recommend consulting a qualified financial advisor, accountant, or business consultant before making any significant business or financial decisions based on projections of any kind.
          </p>
          <p>
            Aura makes no warranty, representation, or guarantee regarding the accuracy, completeness, or suitability of any projection for any specific business purpose.
          </p>

          <h2>4. Acceptable Use</h2>
          <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
          <ul>
            <li>Use the Service in any way that violates applicable local, national, or international law or regulation</li>
            <li>Attempt to probe, scan, or test the vulnerability of our system or network</li>
            <li>Transmit any unsolicited or unauthorized advertising or promotional material</li>
            <li>Attempt to reverse-engineer, decompile, or disassemble any portion of the Service</li>
            <li>Use automated scripts, bots, or scrapers to access or interact with the Service at scale</li>
            <li>Reproduce or redistribute the Service&apos;s branding, design, or source code without written permission</li>
          </ul>

          <h2>5. Intellectual Property</h2>
          <p>
            The Service and all of its original content, features, visual design, brand identity, and functionality are and will remain the exclusive property of Aura SaaS Insights and its licensors. The Service is protected by copyright, trademark, trade dress, and other intellectual property laws. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Aura SaaS Insights.
          </p>
          <p>
            You retain ownership of any data you input into the Service. By using the Service, you grant us a limited, non-exclusive, royalty-free license to process your inputs solely for the purpose of providing the projection functionality described herein.
          </p>

          <h2>6. Third-Party Advertising</h2>
          <p>
            The Service displays advertisements served by Google AdSense and other third-party advertising networks. These advertisements are provided by third parties and are not endorsed by Aura SaaS Insights. We are not responsible for the content of third-party advertisements or for any products or services advertised therein. Your interactions with advertisers found through the Service are solely between you and such advertisers.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AURA SAAS INSIGHTS, ITS OFFICERS, DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
          </p>
          <ul>
            <li>Your access to or use of (or inability to access or use) the Service</li>
            <li>Any conduct or content of any third party on the Service</li>
            <li>Any financial decisions made in reliance on projections generated by the Service</li>
            <li>Unauthorized access, use, or alteration of your transmissions or content</li>
          </ul>
          <p>
            IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRIOR TO THE CLAIM (OR $0 IF YOU HAVE NOT PAID US).
          </p>

          <h2>8. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
          </p>

          <h2>9. Governing Law &amp; Dispute Resolution</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the applicable jurisdiction, without regard to its conflict of law provisions. Any dispute arising from or relating to these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved through binding arbitration in accordance with applicable arbitration rules.
          </p>

          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify or replace these Terms at any time at our sole discretion. When we make material changes, we will update the &quot;Last updated&quot; date at the top of this page. Your continued use of the Service after any changes constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you should discontinue use of the Service.
          </p>

          <h2>11. Contact Us</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at:{' '}
            <a href="mailto:legal@aurarevenue.com">legal@aurarevenue.com</a>
          </p>

        </div>

        <div className="mt-16 pt-8 border-t border-[var(--border-color)]/30 flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between text-sm text-[var(--text-secondary)]">
          <Link href="/" className="hover:text-[var(--accent-color)] transition-colors">&larr; Back to Forecaster</Link>
          <Link href="/privacy" className="hover:text-[var(--accent-color)] transition-colors">Privacy Policy &rarr;</Link>
        </div>
      </div>
    </div>
  );
}
